ROOT_DIR: "data/UCSD/UCSDped1/Train"
IMAGE_TENSOR_SHAPE: [3, 224, 224]
MAE_BACKBONE: "OpenGVLab/VideoMAEv2-Huge"
SEQ_LEN: 16
BATCH_SIZE: 12
DATASET_SHUFFLE: true
EPOCHS: 50
LEARNING_RATE: 0.001
CHECKPOINT_NAME: "weights/UCSDped1_VideoMAE_Huge.pth"
RUN_NAME: "UCSDped1_VideoMAE_Huge"