ROOT_DIR: "data/IPAD/R02/training/frames"
IMAGE_TENSOR_SHAPE: [3, 224, 224]
MAE_BACKBONE: "OpenGVLab/VideoMAEv2-Large"
SEQ_LEN: 16
BATCH_SIZE: 16
DATASET_SHUFFLE: true
EPOCHS: 30
LEARNING_RATE: 0.01
CHECKPOINT_NAME: "weights/IPAD_R02.pth"